name: Hello François
on: workflow_dispatch

env:
  NAME: Alex

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit bonjour"

        if: ${{env.NAME != 'François'}}
        run: echo "Salut mais qui es tu ?, tu n'es pas $NAME ?! Oo!"
      
      - name: "Hello François (steps)"

        if: ${{env.NAME == 'François'}}
        run: echo "Salut $NAME ! Force et Honneur !!!"