name: needs
on:
  workflow_dispatch:
    inputs:
      message:
        default: "event a bien été trigger manuellement"
  pull_request:
      types: opened
      branches:
        - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "1er job"
        if: ${{github.event_name == 'workflow_dispatch'}}
        run: echo "${{github.event.inputs.message}}"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: ${{github.event_name  =='pull_request'}}
    steps:
      - name: PR open
        run: echo"PR open\:${{github.event.pull_request.title}}"