name: fruits

on: workflow_dispatch

jobs:
  Fruits:
    strategy:
      fail-fast: true
      max-parallel : 2
      matrix:
        fruits: [Pomme, Poire, Pêche, Cerise]
        personnes: [Geralt, Ashen One, Tarnished, Link]
    name: fruits/personnes
    runs-on: ubuntu-latest

    steps:
      - name: Manger
        run : echo "${{matrix.personnes}} mange une ${{matrix.fruits}}, et il/elle adore ça !"